# Generated by Django 5.1.6 on 2025-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriscopeDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ugly_name', models.CharField(max_length=200)),
                ('pretty_name', models.CharField(max_length=200)),
                ('search_name', models.CharField(max_length=200)),
                ('outout_prefix', models.CharField(max_length=200)),
                ('output_suffix', models.CharField(max_length=200)),
                ('patient_facing_label', models.CharField(max_length=200)),
                ('patient_facing_description', models.TextField()),
                ('clinician_facing_label', models.CharField(max_length=200)),
                ('clinician_facing_description', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
    ]
