# Generated by Django 5.1.6 on 2025-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periscopedatatype',
            name='ugly_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
