# Generated by Django 5.1.6 on 2025-02-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_periscopedatatype_ugly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periscopedatatype',
            old_name='outout_prefix',
            new_name='output_prefix',
        ),
    ]
