services:
  babel:
    environment:
      - CMD=pipenv run flask --app app:app --debug run --host=0.0.0.0 --port=8070
    develop:
      watch:
        - action: sync
          path: _babel
          target: /app