services:
  clinic:
    environment:
      - CMD=pipenv run python app.py
      # - CMD=pipenv run flask --app app:app --debug run --host=0.0.0.0 --port=8070
      - ENV=development
    develop:
      watch:
        - action: sync
          path: www
          target: /app
