services:
  clinic:
    environment:
      - DEBUG=1
    develop:
      watch:
        - action: sync
          path: app
          target: /app
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - env/development