services:
  clinic:
    environment:
      - CMD=pipenv run python manage.py runserver 0.0.0.0:8070
      # - CMD=sleep infinity
      - ENV=development
    develop:
      watch:
        - action: sync
          path: www
          target: /app
